[package]
name = "bytes_iter"
version = "0.1.1"
authors = ["Isaac Woods <isaac@isaacwoods.tk>"]
description = "Tiny crate for consuming series of bytes from iterators"
repository = "https://github.com/IsaacWoods/bytes-iter"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
